import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const defaultSettings = {
  language: "english",
  sound: true,
  profileView: true,
  themeMode: "bright",
};

const uiThemes = {
  bright: {
    name: "bright",
    colors: {
      gold: "#f1c40f",
      goldDeep: "#d4af37",
      cream: "#f5eec2",
      text: "#ffffff",
      textDark: "#061208",
      panelTop: "rgba(15, 61, 31, 0.9)",
      panelBottom: "rgba(6, 31, 16, 0.84)",
      field: "rgba(0,0,0,0.32)",
      bgTop: "#1f5f26",
      bgMid: "#0b2f18",
      bgLow: "#062211",
      bgBase: "#04170b",
      dotGold: "rgba(241, 196, 15, 0.12)",
      dotWhite: "rgba(245, 238, 194, 0.07)",
      patternWhite: "rgba(245,238,194,0.14)",
      patternGold: "rgba(241,196,15,0.18)",
      gridGold: "rgba(241, 196, 15, 0.04)",
      gridGoldX: "rgba(241, 196, 15, 0.036)",
    },
  },
  dark: {
    name: "dark",
    colors: {
      gold: "#c0842f",
      goldDeep: "#7c4a14",
      cream: "#d8c7a3",
      text: "#f7efe3",
      textDark: "#120b05",
      panelTop: "rgba(38, 22, 30, 0.94)",
      panelBottom: "rgba(18, 12, 18, 0.92)",
      field: "rgba(255,255,255,0.06)",
      bgTop: "#24131e",
      bgMid: "#15111c",
      bgLow: "#0d0b13",
      bgBase: "#050408",
      dotGold: "rgba(192, 132, 47, 0.1)",
      dotWhite: "rgba(216, 199, 163, 0.045)",
      patternWhite: "rgba(216,199,163,0.09)",
      patternGold: "rgba(192,132,47,0.14)",
      gridGold: "rgba(216, 199, 163, 0.035)",
      gridGoldX: "rgba(216, 199, 163, 0.03)",
    },
  },
};

const buildUi = (themeMode) => {
  const theme = uiThemes[themeMode] || uiThemes.bright;
  const { colors } = theme;
  const field = {
    background: `linear-gradient(180deg, ${colors.field}, rgba(255,255,255,0.035))`,
    border: "1px solid rgba(255,255,255,0.16)",
    boxShadow: "0 8px 18px rgba(0,0,0,0.12), inset 0 1px 0 rgba(255,255,255,0.16)",
  };
  const primaryButton = {
    background: `linear-gradient(180deg, ${colors.gold}, ${colors.goldDeep})`,
    border: "1px solid rgba(255,255,255,0.22)",
    boxShadow: "0 10px 22px rgba(0,0,0,0.22), inset 0 1px 0 rgba(255,255,255,0.34)",
    color: colors.textDark,
  };
  const secondaryButton = {
    ...field,
    background: `linear-gradient(180deg, color-mix(in srgb, ${colors.cream} 10%, transparent), rgba(255,255,255,0.04))`,
    color: colors.cream,
  };
  const iconButton = {
    ...secondaryButton,
    color: colors.gold,
  };

  return {
    themeMode: theme.name,
    colors,
    glassPanel: {
      background: `linear-gradient(180deg, ${colors.panelTop}, ${colors.panelBottom})`,
      border: "1px solid rgba(255,255,255,0.14)",
      backdropFilter: "blur(14px)",
      WebkitBackdropFilter: "blur(14px)",
      boxShadow: `0 18px 42px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.24), 0 0 0 1px color-mix(in srgb, ${colors.gold} 14%, transparent)`,
    },
    goldButton: primaryButton,
    primaryButton,
    secondaryButton,
    iconButton,
    field,
    textField: {
      ...field,
      color: colors.text,
      borderRadius: "8px",
      outline: "none",
    },
  };
};

const translations = {
  english: {
    liveTick: "Live Tick",
    settings: "Settings",
    language: "Language",
    sound: "Sound",
    profileView: "Profile view",
    theme: "Theme",
    brightMode: "Bright",
    darkMode: "Dark",
    on: "On",
    off: "Off",
    loading: "Loading...",
    user: "User",
    username: "username",
    userNotFound: "User Not Found",
    balance: "Balance",
    yourBalance: "Your Balance",
    deposit: "Deposit",
    withdraw: "Withdraw",
    play: "Play",
    close: "Close",
    english: "English",
    amharic: "Amharic",
    oromifa: "Oromifa",
    gameRooms: "Game Rooms",
    playWithBot: "Play with Bot",
    teachingBot: "Teaching Bot",
    practiceMode: "Practice mode",
    practiceCoachTitle: "First game steps",
    practiceCoachPick: "Pick one card from the deck or laid pile.",
    practiceCoachLay: "Lay one card back to the table.",
    practiceCoachWatch: "Watch the bot turn, then repeat.",
    practiceCoachWin: "Build 4-3-3-1 and press Win.",
    gameRulesTitle: "How to play",
    gameRulesPick: "On your turn, pick one card from the deck or the laid pile.",
    gameRulesLay: "After picking, lay one card to end your turn.",
    gameRulesGoal: "Arrange your eleven cards into groups of 4-3-3-1 matching ranks.",
    gameRulesJoker: "A joker can extend a natural rank group, but cannot create a group by itself.",
    gameRulesDeclare: "When your hand is valid, press Win to declare it.",
    showCurrentHelp: "Show current step",
    practiceFreeNote: "Free practice. No Birr is charged.",
    createRoom: "Create Room",
    deleteRoom: "Delete Room",
    createAndJoin: "Create & Join",
    creating: "Creating...",
    join: "Join",
    getBack: "Get Back",
    inProgress: "In Progress",
    joinRoom: "Join Room",
    entryFee: "Entry Fee",
    players: "Players",
    roomName: "Room Name",
    roomPlaceholder: "e.g., Weekend Warriors",
    gameType: "Game Type",
    visibility: "Visibility",
    public: "Public",
    private: "Private",
    publicRoomHint: "Public rooms appear in the lobby until they are full.",
    privateRoomHint: "Private rooms stay hidden and can be shared through Telegram.",
    privateRoomShareHint: "Private rooms stay hidden and can be shared through Telegram.",
    privateRoomReady: "Private Room Ready",
    privateLinkReady: "Private Link Ready",
    shareTelegram: "Share on Telegram",
    copyLink: "Copy Link",
    copied: "Copied!",
    copyFailed: "Could not copy link.",
    shareTelegramUnavailable: "Telegram inline sharing is not available here.",
    fillAllFields: "Please fill all fields",
    minRoomEntryError: "Minimum room entry fee is {amount}.",
    minimumRoomEntry: "Minimum room entry",
    failedToJoinRoom: "Failed to join room.",
    failedToCreateRoom: "Failed to create room.",
    confirmJoinTitle: "Join {room}",
    entryFeeLabel: "Entry fee",
    yourBalanceLabel: "Your balance",
    joinNote: "When you join this room, {amount} will be deducted from your balance.",
    insufficientBalance: "Insufficient balance!",
    cancel: "Cancel",
    confirmAndJoin: "Confirm & Join",
    joining: "Joining...",
    payToNumber: "Pay to this number:",
    payToNumbers: "Pay to these numbers:",
    depositCoinRule: "Minimum deposit is {birr}. Game balance is shown in Birr.",
    depositCoinsCredited: "{amount} credited from {birr}.",
    depositCoinsCreditedRounded: "{amount} credited from {birr}. {rounded} was rounded down.",
    receiptInputType: "Choose receipt input type",
    pasteTextLink: "Paste text/link",
    uploadScreenshot: "Upload screenshot",
    pasteReceiptHere: "Paste the message or receipt link here",
    receiptPlaceholder: "Paste receipt text or transaction link...",
    uploadPaymentScreenshot: "Upload payment screenshot",
    chooseDifferentScreenshot: "Choose different screenshot",
    chooseScreenshotImage: "Choose screenshot image",
    screenshotHelper: "PNG, JPG or WEBP up to 5MB",
    selected: "Selected",
    confirmPayment: "I confirm that I made the payment",
    back: "Back",
    checkReceipt: "Check Receipt",
    verifying: "Verifying...",
    verifyingPayment: "Verifying payment...",
    confirmPaymentError: "Please check the confirmation box before submitting.",
    pasteReceiptError: "Please paste your message or receipt link.",
    screenshotError: "Please upload a screenshot first.",
    receiptCheckFailed: "Receipt check failed.",
    screenshotReadFailed: "Could not read screenshot.",
    receiptComplete: "Receipt check complete. Status: {status}.",
    backendFailed: "Failed to connect to backend API.",
    minWithdraw: "Minimum withdraw",
    maxWithdraw: "Maximum withdraw",
    withdrawAmount: "Withdraw Birr",
    withdrawPlaceholder: "Enter Birr to withdraw",
    sending: "Sending...",
    userNotTelegram: "User not found. Please open from Telegram app.",
    minWithdrawError: "Minimum withdraw amount is {amount}.",
    withdrawBalanceError: "Withdraw amount is greater than your balance.",
    withdrawFailed: "Withdraw failed.",
    withdrawSuccess: "Withdraw request sent successfully.",
    withdrawRequestSentInfo: "Your withdrawal request for {amount} has been sent to admin. You will receive a bot message after it is marked Sent.",
    loadingGame: "Loading Game...",
    fee: "Fee",
    pick: "Pick",
    lay: "Lay",
    empty: "Empty",
    opponent: "Opponent",
    player: "Player",
    you: "You",
    waitingForCards: "Waiting for cards...",
    leave: "Leave",
    win: "Win",
    gameOver: "Game Over",
    winner: "Winner",
    pattern: "Pattern",
    reason: "Reason",
    ended: "Ended",
    playAgain: "Play Again",
    playAgainBalanceRequired: "You need at least {fee} to play another round. Deposit Birr to continue.",
    insertCard: "Insert",
    layCard: "Lay",
    laidHistory: "Laid cards",
    joker: "Joker",
    starting: "Starting...",
    notAvailable: "N/A",
    alreadyPicked: "You already picked! You must lay a card.",
    mustPickFirst: "You must pick a card before you can lay one.",
    actionFailed: "Action failed",
    networkError: "Network error. Could not connect to server.",
    winningHandError: "Winning hand must be 4-3-3-1.",
    visibleGameplayName: "Visible gameplay name",
    games: "Games",
    amountPlayed: "Amount played",
    shared: "Shared",
    gotBirr: "Got Birr",
    gotCoins: "Got Birr",
    rewardsLeft: "Left",
    save: "Save",
    shareReward: "Share and get Birr",
    share: "Share",
    shareInviteText: "Play Karta and get Birr.",
    preparingTelegramShare: "Preparing share...",
    telegramShareSent: "Sent: {content}",
    telegramShareCanceled: "Share canceled: {content}",
    telegramShareFallbackOpened: "Telegram opened. Select the Karta invite to send: {content}",
    goToGame: "Go to game",
    privateGameJoinTitle: "Private game invite",
    privateGameJoinWarning: "This is a private game. Confirm before joining; the entry fee will be deducted when the room starts.",
    depositToJoin: "Deposit to join",
    sharedToTelegram: "Shared to selected Telegram chat",
    playersInRoom: "Players in room",
    waitingForPlayersToJoin: "Waiting for players to join.",
    cancelToLobby: "Cancel to lobby",
    profileLoadFailed: "Could not load profile.",
    profileSaveFailed: "Could not save profile.",
    deleteOwnRoomFirst: "Delete your room before joining a new room.",
    leaveCurrentRoomFirst: "Leave your current room before joining a new room.",
    deleteOwnRoomBeforeCreate: "Delete your room before creating a new room.",
    leaveCurrentRoomBeforeCreate: "Leave your current room before creating a new room.",
    invalidServerResponse: "Invalid server response.",
    screenshotPreviewAlt: "Selected payment screenshot preview",
    kartaBannerAlt: "Karta banner {number}",
    jokerPickBlocked: "Joker cards cannot be picked from the laid pile.",
    gameProgress: "Game progress",
    totalToWin: "Total to win",
    currentGame: "Current game",
    completed: "Completed",
    gameRound: "Game {round}",
    totalAmount: "Total amount",
    noCompletedGames: "No completed games yet. Entry fees are refundable until the first winner.",
    leaveGameTitle: "Leave this game?",
    leaveGameText: "Your completed games are already settled. If you leave now, you will be removed from this room and can create or join another room.",
    gamesYouPlayed: "Games you played",
    youWon: "You won",
    youLost: "You lost",
    entryFeesPaid: "Entry fees paid",
    wonAndAdded: "Won and added",
    currentRoundFee: "Current round fee",
    balanceAfterLeaving: "Balance after leaving",
    ok: "OK",
    balanceSummary: "Balance summary",
    balanceSummaryText: "Review your balance and game history before leaving this room.",
    playedWith: "Played with",
    totalRoomAmount: "Total room amount",
    commission: "Commission",
    youReceive: "You receive",
    youReceived: "You received",
    newBalance: "New balance",
    gamesPlayed: "Games played",
    roomInactive: "Room inactive",
    yourVote: "Your vote",
    waiting: "Waiting...",
    continue: "Continue",
    gamePausedWaiting: "Game paused. Waiting for players.",
    jokerBonus: "Joker bonus",
    jokerBonusDetail: "Joker bonus: this round counts double",
    currentBalance: "Current balance",
    birr: "Birr",
    coins: "Birr",
    welcomeGiftTitle: "Welcome gift",
    welcomeGiftText: "You received {amount} for your first start.",
    welcomeGiftButton: "Start playing",
    validHand: "Valid hand",
  },
  amharic: {
    liveTick: "ቀጥታ ቁጥር",
    settings: "ቅንብሮች",
    language: "ቋንቋ",
    sound: "ድምጽ",
    profileView: "ፕሮፋይል እይታ",
    theme: "ገጽታ",
    brightMode: "ብሩህ",
    darkMode: "ጨለማ",
    on: "ክፍት",
    off: "ዝግ",
    loading: "በመጫን ላይ...",
    user: "ተጠቃሚ",
    username: "የተጠቃሚ ስም",
    userNotFound: "ተጠቃሚ አልተገኘም",
    balance: "ቀሪ ሂሳብ",
    yourBalance: "የእርስዎ ቀሪ ሂሳብ",
    deposit: "ገንዘብ አስገባ",
    withdraw: "ገንዘብ አውጣ",
    play: "ተጫወት",
    close: "ዝጋ",
    english: "እንግሊዝኛ",
    amharic: "አማርኛ",
    oromifa: "ኦሮምኛ",
    gameRooms: "የጨዋታ ክፍሎች",
    createRoom: "ክፍል ፍጠር",
    deleteRoom: "ክፍል ሰርዝ",
    createAndJoin: "ፍጠርና ግባ",
    creating: "በመፍጠር ላይ...",
    join: "ግባ",
    getBack: "ተመለስ",
    inProgress: "በሂደት ላይ",
    joinRoom: "ክፍሉን ተቀላቀል",
    entryFee: "መግቢያ ክፍያ",
    players: "ተጫዋቾች",
    roomName: "የክፍል ስም",
    roomPlaceholder: "ለምሳሌ፣ Weekend Warriors",
    gameType: "የጨዋታ አይነት",
    visibility: "ታይነት",
    public: "ይፋዊ",
    private: "የግል",
    publicRoomHint: "ይፋዊ ክፍሎች እስኪሞሉ ድረስ በሎቢ ይታያሉ።",
    privateRoomHint: "የግል ክፍሎች ተደብቀው ይቆያሉ፣ በግብዣ ሊንክ መግባት ይቻላል።",
    privateLinkReady: "የግል ሊንክ ዝግጁ ነው",
    shareTelegram: "በቴሌግራም አጋራ",
    copyLink: "ሊንክ ቅዳ",
    copied: "ተቀድቷል!",
    copyFailed: "ሊንኩን መቅዳት አልተቻለም።",
    fillAllFields: "እባክዎ ሁሉንም ቦታ ይሙሉ",
    failedToJoinRoom: "ክፍሉን መቀላቀል አልተቻለም።",
    failedToCreateRoom: "ክፍል መፍጠር አልተቻለም።",
    confirmJoinTitle: "{room} ተቀላቀል",
    entryFeeLabel: "መግቢያ ክፍያ",
    yourBalanceLabel: "የእርስዎ ቀሪ ሂሳብ",
    joinNote: "ይህን ክፍል ሲቀላቀሉ {amount} ከሂሳብዎ ይቀነሳል።",
    insufficientBalance: "በቂ ቀሪ ሂሳብ የለም!",
    cancel: "ሰርዝ",
    confirmAndJoin: "አረጋግጥና ግባ",
    joining: "በመግባት ላይ...",
    payToNumber: "ወደዚህ ቁጥር ይክፈሉ:",
    payToNumbers: "ወደዚህ ቁጥሮች ይክፈሉ:",
    receiptInputType: "የደረሰኝ ግቤት አይነት ይምረጡ",
    pasteTextLink: "ጽሁፍ/ሊንክ ለጥፍ",
    uploadScreenshot: "ስክሪንሾት ጫን",
    pasteReceiptHere: "መልዕክቱን ወይም የደረሰኝ ሊንኩን እዚህ ለጥፍ",
    receiptPlaceholder: "የደረሰኝ ጽሁፍ ወይም ሊንክ ለጥፍ...",
    uploadPaymentScreenshot: "የክፍያ ስክሪንሾት ጫን",
    chooseDifferentScreenshot: "ሌላ ስክሪንሾት ምረጥ",
    chooseScreenshotImage: "የስክሪንሾት ምስል ምረጥ",
    screenshotHelper: "PNG, JPG ወይም WEBP እስከ 5MB",
    selected: "የተመረጠ",
    confirmPayment: "ክፍያውን እንደፈጸምኩ አረጋግጣለሁ",
    back: "ተመለስ",
    checkReceipt: "ደረሰኝ አረጋግጥ",
    verifying: "በማረጋገጥ ላይ...",
    verifyingPayment: "ክፍያ በማረጋገጥ ላይ...",
    confirmPaymentError: "ከመላክዎ በፊት የማረጋገጫውን ሳጥን ይምረጡ።",
    pasteReceiptError: "እባክዎ መልዕክትዎን ወይም የደረሰኝ ሊንክዎን ይለጥፉ።",
    screenshotError: "እባክዎ መጀመሪያ ስክሪንሾት ይጫኑ።",
    receiptCheckFailed: "የደረሰኝ ማረጋገጫ አልተሳካም።",
    screenshotReadFailed: "ስክሪንሾቱን ማንበብ አልተቻለም።",
    receiptComplete: "የደረሰኝ ማረጋገጫ ተጠናቋል። ሁኔታ: {status}።",
    backendFailed: "ከጀርባ አገልጋይ ጋር መገናኘት አልተቻለም።",
    minWithdraw: "ዝቅተኛ ማውጣት",
    maxWithdraw: "ከፍተኛ ማውጣት",
    withdrawAmount: "የማውጣት መጠን",
    withdrawPlaceholder: "የሚያወጡትን መጠን ያስገቡ",
    sending: "በመላክ ላይ...",
    userNotTelegram: "ተጠቃሚ አልተገኘም። እባክዎ ከቴሌግራም ይክፈቱ።",
    minWithdrawError: "ዝቅተኛው የማውጣት መጠን {amount} ነው።",
    withdrawBalanceError: "የማውጣት መጠን ከቀሪ ሂሳብዎ ይበልጣል።",
    withdrawFailed: "ማውጣት አልተሳካም።",
    withdrawSuccess: "የማውጣት ጥያቄ ተልኳል።",
    loadingGame: "ጨዋታ በመጫን ላይ...",
    fee: "ክፍያ",
    pick: "አንሳ",
    lay: "አስቀምጥ",
    empty: "ባዶ",
    opponent: "ተቃዋሚ",
    player: "ተጫዋች",
    you: "እርስዎ",
    waitingForCards: "ካርዶችን በመጠበቅ ላይ...",
    leave: "ውጣ",
    win: "አሸነፍ",
    gameOver: "ጨዋታው አልቋል",
    winner: "አሸናፊ",
    pattern: "ቅደም ተከተል",
    reason: "ምክንያት",
    ended: "ተጠናቋል",
    playAgain: "እንደገና ተጫወት",
    starting: "በመጀመር ላይ...",
    notAvailable: "የለም",
    alreadyPicked: "ካርድ አንስተዋል! ካርድ ማስቀመጥ አለብዎት።",
    mustPickFirst: "ካርድ ከማስቀመጥዎ በፊት መጀመሪያ ካርድ ያንሱ።",
    actionFailed: "ተግባሩ አልተሳካም",
    networkError: "የኔትወርክ ችግር። ከአገልጋዩ ጋር መገናኘት አልተቻለም።",
    winningHandError: "የማሸነፊያ ካርድ 4-3-3-1 መሆን አለበት።",
    visibleGameplayName: "በጨዋታ የሚታይ ስም",
    games: "ጨዋታዎች",
    amountPlayed: "የተጫወቱበት መጠን",
    shared: "የተጋራ",
    gotBirr: "ያገኙት ብር",
    rewardsLeft: "የቀረ",
    save: "አስቀምጥ",
    shareReward: "አጋራ እና Birr ያግኙ",
    share: "አጋራ",
    shareInviteText: "Karta ይጫወቱ እና Birr ያግኙ።",
    profileLoadFailed: "ፕሮፋይል መጫን አልተቻለም።",
    profileSaveFailed: "ፕሮፋይል ማስቀመጥ አልተቻለም።",
    deleteOwnRoomFirst: "አዲስ ክፍል ከመግባትዎ በፊት የራስዎን ክፍል ይሰርዙ።",
    leaveCurrentRoomFirst: "አዲስ ክፍል ከመግባትዎ በፊት አሁን ካሉበት ክፍል ይውጡ።",
    deleteOwnRoomBeforeCreate: "አዲስ ክፍል ከመፍጠርዎ በፊት የራስዎን ክፍል ይሰርዙ።",
    leaveCurrentRoomBeforeCreate: "አዲስ ክፍል ከመፍጠርዎ በፊት አሁን ካሉበት ክፍል ይውጡ።",
    invalidServerResponse: "የአገልጋይ ምላሽ ትክክል አይደለም።",
    screenshotPreviewAlt: "የተመረጠ የክፍያ ስክሪንሾት ቅድመ እይታ",
    kartaBannerAlt: "Karta ባነር {number}",
    jokerPickBlocked: "ጆከር ካርድ ከተጣለው ክምር ማንሳት አይቻልም።",
    gameProgress: "የጨዋታ ሂደት",
    totalToWin: "ለማሸነፍ ጠቅላላ",
    currentGame: "የአሁኑ ጨዋታ",
    completed: "የተጠናቀቀ",
    gameRound: "ጨዋታ {round}",
    totalAmount: "ጠቅላላ መጠን",
    noCompletedGames: "እስካሁን የተጠናቀቀ ጨዋታ የለም። መጀመሪያው አሸናፊ እስኪገኝ ድረስ መግቢያ ክፍያዎች ይመለሳሉ።",
    leaveGameTitle: "ከዚህ ጨዋታ ይውጡ?",
    leaveGameText: "የተጠናቀቁ ጨዋታዎችዎ ተስተካክለዋል። አሁን ከወጡ ከዚህ ክፍል ይወገዳሉ እና ሌላ ክፍል መፍጠር ወይም መግባት ይችላሉ።",
    gamesYouPlayed: "የተጫወቱት ጨዋታዎች",
    youWon: "ያሸነፉት",
    youLost: "የተሸነፉት",
    entryFeesPaid: "የተከፈለ መግቢያ ክፍያ",
    wonAndAdded: "ያሸነፉት እና የተጨመረ",
    currentRoundFee: "የአሁኑ ዙር ክፍያ",
    balanceAfterLeaving: "ከመውጣት በኋላ ቀሪ ሂሳብ",
    ok: "እሺ",
    balanceSummary: "የቀሪ ሂሳብ ማጠቃለያ",
    balanceSummaryText: "ከዚህ ክፍል ከመውጣትዎ በፊት ቀሪ ሂሳብዎን እና የጨዋታ ታሪክዎን ይመልከቱ።",
    playedWith: "የተጫወቱበት",
    totalRoomAmount: "ጠቅላላ የክፍል መጠን",
    commission: "ኮሚሽን",
    youReceive: "የሚቀበሉት",
    youReceived: "የተቀበሉት",
    newBalance: "አዲስ ቀሪ ሂሳብ",
    gamesPlayed: "የተጫወቱ ጨዋታዎች",
    roomInactive: "ክፍሉ ንቁ አይደለም",
    yourVote: "ድምጽዎ",
    waiting: "በመጠበቅ ላይ...",
    continue: "ቀጥል",
    gamePausedWaiting: "ጨዋታው ቆሟል። ተጫዋቾችን በመጠበቅ ላይ።",
    jokerBonus: "የጆከር ቦነስ",
    jokerBonusDetail: "የጆከር ቦነስ፦ ይህ ዙር ሁለት ጊዜ ይቆጠራል",
    currentBalance: "የአሁኑ ቀሪ ሂሳብ",
    birr: "ብር",
    validHand: "ትክክለኛ ካርድ",
  },
  oromifa: {
    liveTick: "Lakkoofsa kallattii",
    settings: "Sirreeffamoota",
    language: "Afaan",
    sound: "Sagalee",
    profileView: "Mul'isa piroofaayilii",
    theme: "Bifa",
    brightMode: "Ifaa",
    darkMode: "Dukkana",
    on: "Banaa",
    off: "Cufaa",
    loading: "Fe'amaa jira...",
    user: "Fayyadamaa",
    username: "maqaa fayyadamaa",
    userNotFound: "Fayyadamaan hin argamne",
    balance: "Haftee",
    yourBalance: "Haftee kee",
    deposit: "Galchi",
    withdraw: "Baasi",
    play: "Taphadhu",
    close: "Cufi",
    english: "Ingiliffa",
    amharic: "Amaaraa",
    oromifa: "Oromifa",
    gameRooms: "Kutaalee taphaa",
    createRoom: "Kutaa uumi",
    deleteRoom: "Kutaa haqi",
    createAndJoin: "Uumi fi seeni",
    creating: "Uumaa jira...",
    join: "Seeni",
    getBack: "Deebi'i",
    inProgress: "Jira",
    joinRoom: "Kutaa seeni",
    entryFee: "Kaffaltii seensaa",
    players: "Taphattoota",
    roomName: "Maqaa kutaa",
    roomPlaceholder: "fkn., Weekend Warriors",
    gameType: "Gosa taphaa",
    visibility: "Mul'achuu",
    public: "Uummataaf",
    private: "Dhuunfaa",
    publicRoomHint: "Kutaaleen uummataa hanga guutamanitti loobiitti ni mul'atu.",
    privateRoomHint: "Kutaaleen dhuunfaa ni dhokatu; liinkii affeerraa irraa seenamuu danda'u.",
    privateLinkReady: "Liinkiin dhuunfaa qophaa'eera",
    shareTelegram: "Telegram irratti qoodi",
    copyLink: "Liinkii garagalchi",
    copied: "Garagalchame!",
    copyFailed: "Liinkii garagalchuu hin dandeenye.",
    fillAllFields: "Maaloo iddoo hunda guuti",
    failedToJoinRoom: "Kutaa seenuun hin milkoofne.",
    failedToCreateRoom: "Kutaa uumuu hin milkoofne.",
    confirmJoinTitle: "{room} seeni",
    entryFeeLabel: "Kaffaltii seensaa",
    yourBalanceLabel: "Haftee kee",
    joinNote: "Yeroo kutaa kana seentu, {amount} haftee kee irraa hir'ata.",
    insufficientBalance: "Hafteen gahaan hin jiru!",
    cancel: "Dhiisi",
    confirmAndJoin: "Mirkaneessi fi seeni",
    joining: "Seenaa jira...",
    payToNumber: "Lakkoofsa kanaaf kaffali:",
    payToNumbers: "Lakkoofsota kanaaf kaffali:",
    receiptInputType: "Gosa odeeffannoo nagahee filadhu",
    pasteTextLink: "Barreeffama/liinkii maxxansi",
    uploadScreenshot: "Suuraa iskiriinii olkaa'i",
    pasteReceiptHere: "Ergaa yookaan liinkii nagahee asitti maxxansi",
    receiptPlaceholder: "Barreeffama nagahee yookaan liinkii maxxansi...",
    uploadPaymentScreenshot: "Suuraa kaffaltii olkaa'i",
    chooseDifferentScreenshot: "Suuraa biraa filadhu",
    chooseScreenshotImage: "Suuraa iskiriinii filadhu",
    screenshotHelper: "PNG, JPG yookaan WEBP hanga 5MB",
    selected: "Filatame",
    confirmPayment: "Kaffaltii raawwadheera jedhee nan mirkaneessa",
    back: "Deebi'i",
    checkReceipt: "Nagahee mirkaneessi",
    verifying: "Mirkaneessaa jira...",
    verifyingPayment: "Kaffaltii mirkaneessaa jira...",
    confirmPaymentError: "Erguun dura saanduqa mirkaneessaa filadhu.",
    pasteReceiptError: "Maaloo ergaa yookaan liinkii nagahee kee maxxansi.",
    screenshotError: "Maaloo jalqaba suuraa iskiriinii olkaa'i.",
    receiptCheckFailed: "Mirkaneessi nagahee hin milkoofne.",
    screenshotReadFailed: "Suuraa iskiriinii dubbisuun hin danda'amne.",
    receiptComplete: "Mirkaneessi nagahee xumurame. Haala: {status}.",
    backendFailed: "API duubaa waliin wal qunnamuun hin milkoofne.",
    minWithdraw: "Baasi xiqqaa",
    maxWithdraw: "Baasi guddaa",
    withdrawAmount: "Hamma baasuu",
    withdrawPlaceholder: "Hamma baastu galchi",
    sending: "Ergaa jira...",
    userNotTelegram: "Fayyadamaan hin argamne. Maaloo app Telegram irraa bani.",
    minWithdrawError: "Hamma baasuu xiqqaan {amount}.",
    withdrawBalanceError: "Hamma baasuu haftee kee caala.",
    withdrawFailed: "Baasiin hin milkoofne.",
    withdrawSuccess: "Gaaffiin baasuu milkaa'inaan ergame.",
    loadingGame: "Tapha fe'aa jira...",
    fee: "Kaffaltii",
    pick: "Fuudhi",
    lay: "Keessi",
    empty: "Duwwaa",
    opponent: "Morkataa",
    player: "Taphataa",
    you: "Ati",
    waitingForCards: "Kaardota eeggachaa jira...",
    leave: "Bahi",
    win: "Mo'i",
    gameOver: "Taphi xumurame",
    winner: "Mo'ataa",
    pattern: "Paaternii",
    reason: "Sababa",
    ended: "Xumurame",
    playAgain: "Ammas taphadhu",
    starting: "Jalqabaa jira...",
    notAvailable: "Hin jiru",
    alreadyPicked: "Kaardii fudhatteetta! Kaardii tokko kaa'uu qabda.",
    mustPickFirst: "Kaardii kaa'uu dura tokko fudhachuu qabda.",
    actionFailed: "Tarkaanfiin hin milkoofne",
    networkError: "Dogoggora network. Server waliin wal qunnamuun hin danda'amne.",
    winningHandError: "Harki mo'ataa 4-3-3-1 ta'uu qaba.",
    visibleGameplayName: "Maqaa tapha keessatti mul'atu",
    games: "Taphawwan",
    amountPlayed: "Hamma taphatame",
    shared: "Qoodame",
    gotBirr: "Birr argame",
    rewardsLeft: "Hafe",
    save: "Olkaa'i",
    shareReward: "Qoodi, Birr argadhu",
    share: "Qoodi",
    shareInviteText: "Karta taphadhu, Birr argadhu.",
    profileLoadFailed: "Piroofaayilii fe'uun hin danda'amne.",
    profileSaveFailed: "Piroofaayilii olkaa'uun hin danda'amne.",
    deleteOwnRoomFirst: "Kutaa kee haqiitii kutaa haaraa seeni.",
    leaveCurrentRoomFirst: "Kutaa ammaa keessaa ba'iitii kutaa haaraa seeni.",
    deleteOwnRoomBeforeCreate: "Kutaa haaraa uumuu dura kutaa kee haqi.",
    leaveCurrentRoomBeforeCreate: "Kutaa haaraa uumuu dura kutaa ammaa keessaa ba'i.",
    invalidServerResponse: "Deebiin server sirrii miti.",
    screenshotPreviewAlt: "Durargii suuraa kaffaltii filatame",
    kartaBannerAlt: "Baannerii Karta {number}",
    jokerPickBlocked: "Kaardii Joker tuula kaa'ame irraa fudhachuun hin danda'amu.",
    gameProgress: "Adeemsa taphaa",
    totalToWin: "Waliigala mo'achuuf",
    currentGame: "Tapha ammaa",
    completed: "Xumurame",
    gameRound: "Tapha {round}",
    totalAmount: "Hamma waliigalaa",
    noCompletedGames: "Taphni xumurame hanga ammaatti hin jiru. Kaffaltiin seensaa hanga mo'ataan jalqabaa argamutti deebifamuu danda'a.",
    leaveGameTitle: "Tapha kana keessaa baataa?",
    leaveGameText: "Taphawwan xumuraman kee duraan sirreeffamaniiru. Amma yoo baate, kutaa kana keessaa ni haqamta; kutaa biraa uumuu yookaan seenuu dandeessa.",
    gamesYouPlayed: "Taphawwan taphatte",
    youWon: "Ati moote",
    youLost: "Ati mo'amte",
    entryFeesPaid: "Kaffaltii seensaa kaffalame",
    wonAndAdded: "Mo'amee dabalame",
    currentRoundFee: "Kaffaltii marsaa ammaa",
    balanceAfterLeaving: "Haftee erga baatee booda",
    ok: "Tole",
    balanceSummary: "Cuunfaa haftee",
    balanceSummaryText: "Kutaa kana keessaa ba'uu dura haftee fi seenaa tapha kee ilaali.",
    playedWith: "Kan itti taphatte",
    totalRoomAmount: "Hamma waliigalaa kutaa",
    commission: "Komishinii",
    youReceive: "Kan ati argattu",
    youReceived: "Kan ati argatte",
    newBalance: "Haftee haaraa",
    gamesPlayed: "Taphawwan taphataman",
    roomInactive: "Kutaan hin socho'u",
    yourVote: "Sagalee kee",
    waiting: "Eegaa jira...",
    continue: "Itti fufi",
    gamePausedWaiting: "Taphi dhaabbateera. Taphattoota eegaa jira.",
    jokerBonus: "Boonsii Joker",
    jokerBonusDetail: "Boonsii Joker: marsaan kun dachaa lama lakkaa'ama",
    currentBalance: "Haftee ammaa",
    birr: "Birr",
    validHand: "Harka sirrii",
  },
};

const SettingsContext = createContext(null);

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState(() => {
    try {
      const savedSettings = localStorage.getItem("kartaSettings");
      return savedSettings ? { ...defaultSettings, ...JSON.parse(savedSettings) } : defaultSettings;
    } catch (error) {
      return defaultSettings;
    }
  });

  useEffect(() => {
    localStorage.setItem("kartaSettings", JSON.stringify(settings));
  }, [settings]);

  useEffect(() => {
    const ui = buildUi(settings.themeMode);
    const root = document.documentElement;
    const { colors } = ui;

    root.dataset.kartaTheme = ui.themeMode;
    root.style.setProperty("--karta-gold", colors.gold);
    root.style.setProperty("--karta-gold-deep", colors.goldDeep);
    root.style.setProperty("--karta-cream", colors.cream);
    root.style.setProperty("--karta-text", colors.text);
    root.style.setProperty("--karta-text-dark", colors.textDark);
    root.style.setProperty("--karta-field", colors.field);
    root.style.setProperty("--karta-bg-top", colors.bgTop);
    root.style.setProperty("--karta-bg-mid", colors.bgMid);
    root.style.setProperty("--karta-bg-low", colors.bgLow);
    root.style.setProperty("--karta-bg-base", colors.bgBase);
    root.style.setProperty("--karta-grid-gold", colors.gridGold);
    root.style.setProperty("--karta-grid-gold-x", colors.gridGoldX);
    root.style.setProperty("--karta-dot-gold", colors.dotGold);
    root.style.setProperty("--karta-dot-white", colors.dotWhite);
    root.style.setProperty("--karta-pattern-white", colors.patternWhite);
    root.style.setProperty("--karta-pattern-gold", colors.patternGold);
  }, [settings.themeMode]);

  const updateSetting = (key, value) => {
    setSettings((currentSettings) => ({
      ...currentSettings,
      [key]: value,
    }));
  };

  const value = useMemo(() => {
    const activeTranslations = translations[settings.language] || translations.english;
    const ui = buildUi(settings.themeMode);

    return {
      settings,
      updateSetting,
      ui,
      t: (key, params = {}) => {
        const template = activeTranslations[key] || translations.english[key] || key;
        return Object.entries(params).reduce(
          (text, [paramKey, paramValue]) => text.replaceAll(`{${paramKey}}`, paramValue),
          template
        );
      },
    };
  }, [settings]);

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error("useSettings must be used inside SettingsProvider");
  }

  return context;
}
