import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const defaultSettings = {
  language: "english",
  sound: true,
  profileView: true,
  themeMode: "bright",
};

const uiThemes = {
  bright: {
    name: "bright",
    colors: {
      gold: "#f1c40f",
      goldDeep: "#d4af37",
      cream: "#f5eec2",
      text: "#ffffff",
      textDark: "#061208",
      panelTop: "rgba(15, 61, 31, 0.9)",
      panelBottom: "rgba(6, 31, 16, 0.84)",
      field: "rgba(0,0,0,0.32)",
      bgTop: "#1f5f26",
      bgMid: "#0b2f18",
      bgLow: "#062211",
      bgBase: "#04170b",
      dotGold: "rgba(241, 196, 15, 0.12)",
      dotWhite: "rgba(245, 238, 194, 0.07)",
      patternWhite: "rgba(245,238,194,0.14)",
      patternGold: "rgba(241,196,15,0.18)",
      gridGold: "rgba(241, 196, 15, 0.04)",
      gridGoldX: "rgba(241, 196, 15, 0.036)",
    },
  },
  dark: {
    name: "dark",
    colors: {
      gold: "#c0842f",
      goldDeep: "#7c4a14",
      cream: "#d8c7a3",
      text: "#f7efe3",
      textDark: "#120b05",
      panelTop: "rgba(38, 22, 30, 0.94)",
      panelBottom: "rgba(18, 12, 18, 0.92)",
      field: "rgba(255,255,255,0.06)",
      bgTop: "#24131e",
      bgMid: "#15111c",
      bgLow: "#0d0b13",
      bgBase: "#050408",
      dotGold: "rgba(192, 132, 47, 0.1)",
      dotWhite: "rgba(216, 199, 163, 0.045)",
      patternWhite: "rgba(216,199,163,0.09)",
      patternGold: "rgba(192,132,47,0.14)",
      gridGold: "rgba(216, 199, 163, 0.035)",
      gridGoldX: "rgba(216, 199, 163, 0.03)",
    },
  },
};

const buildUi = (themeMode) => {
  const theme = uiThemes[themeMode] || uiThemes.bright;
  const { colors } = theme;
  const field = {
    background: `linear-gradient(180deg, ${colors.field}, rgba(255,255,255,0.035))`,
    border: "1px solid rgba(255,255,255,0.16)",
    boxShadow: "0 8px 18px rgba(0,0,0,0.12), inset 0 1px 0 rgba(255,255,255,0.16)",
  };
  const primaryButton = {
    background: `linear-gradient(180deg, ${colors.gold}, ${colors.goldDeep})`,
    border: "1px solid rgba(255,255,255,0.22)",
    boxShadow: "0 10px 22px rgba(0,0,0,0.22), inset 0 1px 0 rgba(255,255,255,0.34)",
    color: colors.textDark,
  };
  const secondaryButton = {
    ...field,
    background: `linear-gradient(180deg, color-mix(in srgb, ${colors.cream} 10%, transparent), rgba(255,255,255,0.04))`,
    color: colors.cream,
  };
  const iconButton = {
    ...secondaryButton,
    color: colors.gold,
  };

  return {
    themeMode: theme.name,
    colors,
    glassPanel: {
      background: `linear-gradient(180deg, ${colors.panelTop}, ${colors.panelBottom})`,
      border: "1px solid rgba(255,255,255,0.14)",
      backdropFilter: "blur(14px)",
      WebkitBackdropFilter: "blur(14px)",
      boxShadow: `0 18px 42px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.24), 0 0 0 1px color-mix(in srgb, ${colors.gold} 14%, transparent)`,
    },
    goldButton: primaryButton,
    primaryButton,
    secondaryButton,
    iconButton,
    field,
    textField: {
      ...field,
      color: colors.text,
      borderRadius: "8px",
      outline: "none",
    },
  };
};

const translations = {
  english: {
    liveTick: "Live Tick",
    settings: "Settings",
    language: "Language",
    sound: "Sound",
    syncingAction: "Syncing move...",
    profileView: "Profile view",
    theme: "Theme",
    brightMode: "Bright",
    darkMode: "Dark",
    on: "On",
    off: "Off",
    loading: "Loading...",
    user: "User",
    username: "username",
    userNotFound: "User Not Found",
    balance: "Balance",
    yourBalance: "Your Balance",
    deposit: "Deposit",
    withdraw: "Withdraw",
    play: "Play",
    close: "Close",
    english: "English",
    amharic: "Amharic",
    oromifa: "Oromifa",
    gameRooms: "Game Rooms",
    playWithBot: "Play with Bot",
    teachingBot: "Teaching Bot",
    practiceMode: "Practice mode",
    practiceCoachTitle: "First game steps",
    practiceCoachPick: "Pick one card from the deck or laid pile.",
    practiceCoachLay: "Lay one card back to the table.",
    practiceCoachWatch: "Watch the bot turn, then repeat.",
    practiceCoachWin: "Build 4-3-3-1 and press Win.",
    gameRulesTitle: "How to play",
    gameRulesPick: "On your turn, pick one card from the deck or the laid pile.",
    gameRulesLay: "After picking, lay one card to end your turn.",
    gameRulesGoal: "Arrange your eleven cards into groups of 4-3-3-1 matching ranks.",
    gameRulesJoker: "A joker can extend a natural rank group, but cannot create a group by itself.",
    gameRulesDeclare: "When your hand is valid, press Win to declare it.",
    showCurrentHelp: "Show current step",
    practiceFreeNote: "Free practice. No Birr is charged.",
    createRoom: "Create Room",
    deleteRoom: "Delete Room",
    createAndJoin: "Create & Join",
    creating: "Creating...",
    join: "Join",
    getBack: "Get Back",
    inProgress: "In Progress",
    joinRoom: "Join Room",
    entryFee: "Entry Fee",
    players: "Players",
    roomName: "Room Name",
    roomPlaceholder: "e.g., Weekend Warriors",
    gameType: "Game Type",
    visibility: "Visibility",
    public: "Public",
    private: "Private",
    publicRoomHint: "Public rooms appear in the lobby until they are full.",
    privateRoomHint: "Private rooms stay hidden and can be shared through Telegram.",
    privateRoomShareHint: "Private rooms stay hidden and can be shared through Telegram.",
    privateRoomReady: "Private Room Ready",
    privateLinkReady: "Private Link Ready",
    shareTelegram: "Share on Telegram",
    copyLink: "Copy Link",
    copied: "Copied!",
    copyFailed: "Could not copy link.",
    shareTelegramUnavailable: "Telegram inline sharing is not available here.",
    fillAllFields: "Please fill all fields",
    minRoomEntryError: "Minimum room entry fee is {amount}, and it must be a multiple of 5 Birr.",
    minimumRoomEntry: "Minimum room entry",
    failedToJoinRoom: "Failed to join room.",
    failedToCreateRoom: "Failed to create room.",
    confirmJoinTitle: "Join {room}",
    entryFeeLabel: "Entry fee",
    yourBalanceLabel: "Your balance",
    joinNote: "When you join this room, {amount} will be deducted from your balance.",
    insufficientBalance: "Insufficient balance!",
    cancel: "Cancel",
    confirmAndJoin: "Confirm & Join",
    joining: "Joining...",
    payToNumber: "Pay to this number:",
    payToNumbers: "Pay to these numbers:",
    selectPaymentMethod: "Select payment method",
    paymentMethodRequired: "Please select one payment method.",
    payAmountWithFollowingNumber: "Pay your amount with {method} to the following number:",
    depositStepPay: "Pay using the selected payment method to the number shown below.",
    depositStepReceipt: "Copy and paste the receipt message/link, or upload a clear payment screenshot.",
    depositStepConfirm: "Confirm that you paid, then select Check Receipt.",
    depositSuccessTitle: "Payment successful",
    goHome: "Go to home",
    depositBirrCredited: "{amount} credited from {birr}.",
    receiptInputType: "Choose receipt input type",
    pasteTextLink: "Paste text/link",
    uploadScreenshot: "Upload screenshot",
    pasteReceiptHere: "Paste the message or receipt link here",
    receiptPlaceholder: "Paste receipt text or transaction link...",
    uploadPaymentScreenshot: "Upload payment screenshot",
    chooseDifferentScreenshot: "Choose different screenshot",
    chooseScreenshotImage: "Choose screenshot image",
    screenshotHelper: "PNG, JPG or WEBP up to 5MB",
    selected: "Selected",
    confirmPayment: "I confirm that I made the payment",
    back: "Back",
    checkReceipt: "Check Receipt",
    verifying: "Verifying...",
    verifyingPayment: "Verifying payment...",
    confirmPaymentError: "Please check the confirmation box before submitting.",
    pasteReceiptError: "Please paste your message or receipt link.",
    screenshotError: "Please upload a screenshot first.",
    receiptCheckFailed: "Receipt check failed.",
    screenshotReadFailed: "Could not read screenshot.",
    receiptComplete: "Receipt check complete. Status: {status}.",
    backendFailed: "Failed to connect to backend API.",
    minWithdraw: "Minimum withdraw",
    maxWithdraw: "Maximum withdraw",
    dailyWithdrawalLimit: "Daily withdrawal limit",
    unlimited: "Unlimited",
    lockedGiftBalance: "Gift/share rewards locked",
    withdrawAmount: "Withdraw Birr",
    withdrawPlaceholder: "Enter Birr to withdraw",
    withdrawPhone: "Withdrawal phone number",
    withdrawPhonePlaceholder: "09XXXXXXXX or +2519XXXXXXXX",
    withdrawPhoneError: "Enter a valid Ethiopian number: 09/07 followed by 8 digits, or use +251.",
    withdrawPhoneWarning: "Check this number carefully. Money sent to a wrong phone number cannot be returned.",
    sending: "Sending...",
    userNotTelegram: "User not found. Please open from Telegram app.",
    minWithdrawError: "Minimum withdraw amount is {amount}.",
    withdrawBalanceError: "Withdraw amount is greater than your withdrawable balance.",
    withdrawGamesRule: "Complete at least {count} games before withdrawing.",
    withdrawActivityRule: "Play at least {games} games across {days} different days before withdrawing.",
    withdrawReserveRule: "Keep at least {amount} in your balance after withdrawing.",
    withdrawGamesRequiredError: "Play {remaining} more game(s). You can withdraw after completing {required} games.",
    withdrawActivityRequiredError: "Keep playing before withdrawing. Complete at least {required} games across {daysRequired} different days. You still need {remaining} game(s) and {daysRemaining} play day(s).",
    withdrawReserveError: "You must keep at least {amount} in your balance after withdrawing.",
    withdrawDailyLimitError: "Your current daily withdrawal limit is {amount}.",
    withdrawFailed: "Withdraw failed.",
    withdrawSuccess: "Withdraw request sent successfully.",
    withdrawRequestSentInfo: "Withdrawal has been sent. It will be completed in less than 24 hours.",
    withdrawUnavailable: "Withdrawals are not available right now. Please try again later.",
    loadingGame: "Loading Game...",
    fee: "Fee",
    pick: "Pick",
    lay: "Lay",
    empty: "Empty",
    opponent: "Opponent",
    player: "Player",
    you: "You",
    waitingForCards: "Waiting for cards...",
    leave: "Leave",
    win: "Win",
    gameOver: "Game Over",
    victoryTitle: "You won!",
    defeatTitle: "Good game!",
    winningCards: "Winning cards",
    losingCards: "Final cards",
    winAmount: "Win amount",
    winner: "Winner",
    pattern: "Pattern",
    reason: "Reason",
    ended: "Ended",
    playAgain: "Play Again",
    rematchReadyUp: "Ready for another round?",
    rematchLobby: "Rematch lobby",
    joinNextRound: "Join the next round",
    recruitmentPaused: "Paused — waiting for a new player",
    countdownHeldByCreator: "Paused by creator",
    holdCountdown: "Hold",
    resumeCountdown: "Resume",
    feeUpdatedAlert: "Fee changed",
    feeUpdatedReagree: "Re-agree required",
    rematchReturnedToLobby: "Rematch cancelled — room returned to lobby.",
    nextRoundFee: "Entry",
    updateFee: "Set",
    addPlayer: "Add player",
    cancelAddPlayer: "Cancel adding player",
    agreeAndPlay: "Agree & Play",
    rematchStartsIn: "Respond within {seconds}s",
    resolvingRematch: "Updating the next-round players...",
    rematchReady: "Ready",
    rematchWaiting: "Waiting",
    waitingForPlayers: "Waiting for players",
    rematchRemovedTitle: "Removed from rematch",
    rematchRemovedNoResponse: "You did not respond within 40 seconds. The ready players continued without you.",
    rematchRemovedBalance: "Your balance was not enough for the next entry fee, so the ready players continued without you.",
    rematchLeftMessage: "You left the rematch without any deduction.",
    goToLobby: "Go to lobby",
    playAgainBalanceRequired: "You need at least {fee} to play another round. Deposit Birr to continue.",
    insertCard: "Insert",
    layCard: "Lay",
    laidHistory: "Laid cards",
    joker: "Joker",
    starting: "Starting...",
    notAvailable: "N/A",
    alreadyPicked: "You already picked! You must lay a card.",
    mustPickFirst: "You must pick a card before you can lay one.",
    actionFailed: "Action failed",
    networkError: "Network error. Could not connect to server.",
    winningHandError: "Winning hand must be 4-3-3-1.",
    visibleGameplayName: "Visible gameplay name",
    games: "Games",
    amountPlayed: "Amount played",
    shared: "Shared",
    gotBirr: "Got Birr",
    rewardsLeft: "Left",
    save: "Save",
    shareReward: "Share and get Birr",
    share: "Share",
    shareInviteText: "Play Carta and get Birr.",
    preparingTelegramShare: "Preparing share...",
    telegramShareSent: "Sent: {content}",
    telegramShareCanceled: "Share canceled: {content}",
    telegramShareFallbackOpened: "Telegram opened. Select the Carta invite to send: {content}",
    goToGame: "Go to game",
    privateGameJoinTitle: "Private game invite",
    privateGameJoinWarning: "This is a private game. Confirm before joining; the entry fee will be deducted when the room starts.",
    depositToJoin: "Deposit to join",
    sharedToTelegram: "Shared to selected Telegram chat",
    playersInRoom: "Players in room",
    waitingForPlayersToJoin: "Waiting for players to join.",
    cancelToLobby: "Cancel to lobby",
    profileLoadFailed: "Could not load profile.",
    profileSaveFailed: "Could not save profile.",
    deleteOwnRoomFirst: "Delete your room before joining a new room.",
    leaveCurrentRoomFirst: "Leave your current room before joining a new room.",
    deleteOwnRoomBeforeCreate: "Delete your room before creating a new room.",
    leaveCurrentRoomBeforeCreate: "Leave your current room before creating a new room.",
    invalidServerResponse: "Invalid server response.",
    screenshotPreviewAlt: "Selected payment screenshot preview",
    kartaBannerAlt: "Carta banner {number}",
    jokerPickBlocked: "Joker cards cannot be picked from the laid pile.",
    gameProgress: "Game progress",
    gameHistory: "Game history",
    totalToWin: "Total to win",
    currentGame: "Current game",
    completed: "Completed",
    gameRound: "Game {round}",
    totalAmount: "Total amount",
    noCompletedGames: "No completed games yet. Entry fees are refundable until the first winner.",
    leaveGameTitle: "Leave this game?",
    leaveGameText: "Your completed games are already settled. If you leave now, you will be removed from this room and can create or join another room.",
    leavePenaltyWarning: "Warning: If you leave now, half of the entry fee ({amount}) will be deducted from your account and will not be refunded.",
    confirmLeaveYes: "Yes, leave",
    opponentNotRespondingTitle: "Player is not responding",
    opponentNotRespondingText: "{player} has not played for at least five minutes.",
    leaveWithoutDeductionNotice: "You can leave now without any deduction from your entry fee.",
    leaveWithoutDeduction: "Leave without deduction",
    continueWaiting: "Continue waiting",
    timeoutNotReached: "The five-minute timeout has not been reached. Nothing was deducted.",
    gamesYouPlayed: "Games you played",
    youWon: "You won",
    youLost: "You lost",
    entryFeesPaid: "Entry fees paid",
    wonAndAdded: "Won and added",
    currentRoundFee: "Current round fee",
    balanceAfterLeaving: "Balance after leaving",
    ok: "OK",
    balanceSummary: "Balance summary",
    balanceSummaryText: "Review your balance and game history before leaving this room.",
    playedWith: "Played with",
    totalRoomAmount: "Total room amount",
    youReceive: "You receive",
    youReceived: "You received",
    newBalance: "New balance",
    gamesPlayed: "Games played",
    roomInactive: "Room inactive",
    yourVote: "Your vote",
    waiting: "Waiting...",
    continue: "Continue",
    gamePausedWaiting: "Game paused. Waiting for players.",
    jokerBonus: "Joker bonus",
    jokerBonusDetail: "Joker bonus: this round counts double",
    currentBalance: "Current balance",
    birr: "Birr",
    welcomeGiftTitle: "Welcome gift",
    welcomeGiftText: "You received {amount} for your first start.",
    welcomeGiftButton: "Start playing",
    referralRewardTitle: "Referral reward added",
    referralRewardText: "{player} joined using your referral. {amount} was added to your balance.",
    referralRewardButton: "Great!",
    newPlayer: "A new player",
    validHand: "Valid hand",
    callPlayer: "Call player",
    callPlayerWait: "After you lay a card, wait 10 seconds to call the next player.",
    playerCallSent: "Call sent to {player}.",
    playerCallNotification: "{player} is calling you to play.",
  },
  amharic: {
    liveTick: "ቀጥታ ቁጥር",
    settings: "ቅንብሮች",
    language: "ቋንቋ",
    sound: "ድምጽ",
    syncingAction: "እርምጃው እየተመሳሰለ ነው...",
    profileView: "ፕሮፋይል እይታ",
    theme: "ገጽታ",
    brightMode: "ብሩህ",
    darkMode: "ጨለማ",
    on: "ክፍት",
    off: "ዝግ",
    loading: "በመጫን ላይ...",
    user: "ተጠቃሚ",
    username: "የተጠቃሚ ስም",
    userNotFound: "ተጠቃሚ አልተገኘም",
    balance: "ቀሪ ሂሳብ",
    yourBalance: "የእርስዎ ቀሪ ሂሳብ",
    deposit: "ገንዘብ አስገባ",
    withdraw: "ገንዘብ አውጣ",
    play: "ተጫወት",
    close: "ዝጋ",
    english: "እንግሊዝኛ",
    amharic: "አማርኛ",
    oromifa: "ኦሮምኛ",
    gameRooms: "የጨዋታ ክፍሎች",
    createRoom: "ክፍል ፍጠር",
    deleteRoom: "ክፍል ሰርዝ",
    createAndJoin: "ፍጠርና ግባ",
    creating: "በመፍጠር ላይ...",
    join: "ግባ",
    getBack: "ተመለስ",
    inProgress: "በሂደት ላይ",
    joinRoom: "ክፍሉን ተቀላቀል",
    entryFee: "መግቢያ ክፍያ",
    players: "ተጫዋቾች",
    roomName: "የክፍል ስም",
    roomPlaceholder: "ለምሳሌ፣ Weekend Warriors",
    gameType: "የጨዋታ አይነት",
    visibility: "ታይነት",
    public: "ይፋዊ",
    private: "የግል",
    publicRoomHint: "ይፋዊ ክፍሎች እስኪሞሉ ድረስ በሎቢ ይታያሉ።",
    privateRoomHint: "የግል ክፍሎች ተደብቀው ይቆያሉ፣ በግብዣ ሊንክ መግባት ይቻላል።",
    privateLinkReady: "የግል ሊንክ ዝግጁ ነው",
    shareTelegram: "በቴሌግራም አጋራ",
    copyLink: "ሊንክ ቅዳ",
    copied: "ተቀድቷል!",
    copyFailed: "ሊንኩን መቅዳት አልተቻለም።",
    fillAllFields: "እባክዎ ሁሉንም ቦታ ይሙሉ",
    failedToJoinRoom: "ክፍሉን መቀላቀል አልተቻለም።",
    failedToCreateRoom: "ክፍል መፍጠር አልተቻለም።",
    confirmJoinTitle: "{room} ተቀላቀል",
    entryFeeLabel: "መግቢያ ክፍያ",
    yourBalanceLabel: "የእርስዎ ቀሪ ሂሳብ",
    joinNote: "ይህን ክፍል ሲቀላቀሉ {amount} ከሂሳብዎ ይቀነሳል።",
    insufficientBalance: "በቂ ቀሪ ሂሳብ የለም!",
    cancel: "ሰርዝ",
    confirmAndJoin: "አረጋግጥና ግባ",
    joining: "በመግባት ላይ...",
    payToNumber: "ወደዚህ ቁጥር ይክፈሉ:",
    payToNumbers: "ወደዚህ ቁጥሮች ይክፈሉ:",
    selectPaymentMethod: "የክፍያ መንገድ ይምረጡ",
    paymentMethodRequired: "እባክዎ አንድ የክፍያ መንገድ ይምረጡ።",
    payAmountWithFollowingNumber: "መጠኑን በ{method} ወደሚከተለው ቁጥር ይክፈሉ:",
    depositStepPay: "በተመረጠው የክፍያ መንገድ ከታች ወዳለው ቁጥር ይክፈሉ።",
    depositStepReceipt: "የደረሰኙን መልዕክት/ሊንክ ይለጥፉ ወይም ግልጽ የክፍያ ስክሪንሾት ይጫኑ።",
    depositStepConfirm: "ክፍያውን እንደፈጸሙ ያረጋግጡና ደረሰኝ አረጋግጥን ይምረጡ።",
    depositSuccessTitle: "ክፍያው ተሳክቷል",
    goHome: "ወደ መነሻ ሂድ",
    receiptInputType: "የደረሰኝ ግቤት አይነት ይምረጡ",
    pasteTextLink: "ጽሁፍ/ሊንክ ለጥፍ",
    uploadScreenshot: "ስክሪንሾት ጫን",
    pasteReceiptHere: "መልዕክቱን ወይም የደረሰኝ ሊንኩን እዚህ ለጥፍ",
    receiptPlaceholder: "የደረሰኝ ጽሁፍ ወይም ሊንክ ለጥፍ...",
    uploadPaymentScreenshot: "የክፍያ ስክሪንሾት ጫን",
    chooseDifferentScreenshot: "ሌላ ስክሪንሾት ምረጥ",
    chooseScreenshotImage: "የስክሪንሾት ምስል ምረጥ",
    screenshotHelper: "PNG, JPG ወይም WEBP እስከ 5MB",
    selected: "የተመረጠ",
    confirmPayment: "ክፍያውን እንደፈጸምኩ አረጋግጣለሁ",
    back: "ተመለስ",
    checkReceipt: "ደረሰኝ አረጋግጥ",
    verifying: "በማረጋገጥ ላይ...",
    verifyingPayment: "ክፍያ በማረጋገጥ ላይ...",
    confirmPaymentError: "ከመላክዎ በፊት የማረጋገጫውን ሳጥን ይምረጡ።",
    pasteReceiptError: "እባክዎ መልዕክትዎን ወይም የደረሰኝ ሊንክዎን ይለጥፉ።",
    screenshotError: "እባክዎ መጀመሪያ ስክሪንሾት ይጫኑ።",
    receiptCheckFailed: "የደረሰኝ ማረጋገጫ አልተሳካም።",
    screenshotReadFailed: "ስክሪንሾቱን ማንበብ አልተቻለም።",
    receiptComplete: "የደረሰኝ ማረጋገጫ ተጠናቋል። ሁኔታ: {status}።",
    backendFailed: "ከጀርባ አገልጋይ ጋር መገናኘት አልተቻለም።",
    minWithdraw: "ዝቅተኛ ማውጣት",
    maxWithdraw: "ከፍተኛ ማውጣት",
    dailyWithdrawalLimit: "የዕለት ማውጣት ገደብ",
    unlimited: "ያልተገደበ",
    lockedGiftBalance: "የስጦታ/ማጋራት ሽልማት ተቆልፏል",
    withdrawAmount: "የማውጣት መጠን",
    withdrawPlaceholder: "የሚያወጡትን መጠን ያስገቡ",
    sending: "በመላክ ላይ...",
    userNotTelegram: "ተጠቃሚ አልተገኘም። እባክዎ ከቴሌግራም ይክፈቱ።",
    minWithdrawError: "ዝቅተኛው የማውጣት መጠን {amount} ነው።",
    withdrawBalanceError: "የማውጣት መጠን ከሚወጣው ቀሪ ሂሳብዎ ይበልጣል።",
    withdrawGamesRule: "ገንዘብ ከማውጣትዎ በፊት ቢያንስ {count} ጨዋታዎችን ያጠናቅቁ።",
    withdrawActivityRule: "ገንዘብ ከማውጣትዎ በፊት በ{days} የተለያዩ ቀናት ቢያንስ {games} ጨዋታዎችን ይጫወቱ።",
    withdrawReserveRule: "ካወጡ በኋላ ቢያንስ {amount} በሂሳብዎ ያስቀሩ።",
    withdrawGamesRequiredError: "ተጨማሪ {remaining} ጨዋታ(ዎች) ይጫወቱ። {required} ጨዋታዎችን ካጠናቀቁ በኋላ ማውጣት ይችላሉ።",
    withdrawActivityRequiredError: "ገንዘብ ከማውጣትዎ በፊት መጫወትዎን ይቀጥሉ። በ{daysRequired} የተለያዩ ቀናት ቢያንስ {required} ጨዋታዎችን ያጠናቅቁ። ተጨማሪ {remaining} ጨዋታ እና {daysRemaining} የመጫወቻ ቀን ያስፈልግዎታል።",
    withdrawReserveError: "ካወጡ በኋላ ቢያንስ {amount} በሂሳብዎ ማስቀረት አለብዎት።",
    withdrawDailyLimitError: "የአሁኑ የዕለት ማውጣት ገደብዎ {amount} ነው።",
    withdrawFailed: "ማውጣት አልተሳካም።",
    withdrawSuccess: "የማውጣት ጥያቄ ተልኳል።",
    withdrawRequestSentInfo: "የገንዘብ ማውጣት ጥያቄዎ ተልኳል። ከ24 ሰዓት ባነሰ ጊዜ ውስጥ ይጠናቀቃል።",
    withdrawUnavailable: "ገንዘብ ማውጣት አሁን አይሰራም። እባክዎ ቆይተው እንደገና ይሞክሩ።",
    loadingGame: "ጨዋታ በመጫን ላይ...",
    fee: "ክፍያ",
    pick: "አንሳ",
    lay: "አስቀምጥ",
    empty: "ባዶ",
    opponent: "ተቃዋሚ",
    player: "ተጫዋች",
    you: "እርስዎ",
    waitingForCards: "ካርዶችን በመጠበቅ ላይ...",
    leave: "ውጣ",
    win: "አሸነፍ",
    gameOver: "ጨዋታው አልቋል",
    victoryTitle: "አሸነፉ!",
    defeatTitle: "ጥሩ ጨዋታ!",
    winningCards: "የአሸናፊው ካርዶች",
    losingCards: "የመጨረሻ ካርዶች",
    winAmount: "የድል መጠን",
    winner: "አሸናፊ",
    pattern: "ቅደም ተከተል",
    reason: "ምክንያት",
    ended: "ተጠናቋል",
    playAgain: "እንደገና ተጫወት",
    rematchReadyUp: "ሌላ ዙር ለመጫወት ዝግጁ ነዎት?",
    rematchLobby: "የድጋሚ ጨዋታ ሎቢ",
    joinNextRound: "ቀጣዩን ዙር ይቀላቀሉ",
    recruitmentPaused: "ቆሟል — አዲስ ተጫዋች",
    countdownHeldByCreator: "በፈጣሪ ቆሟል",
    holdCountdown: "አቁም",
    resumeCountdown: "ቀጥል",
    feeUpdatedAlert: "ክፍያ ተቀይሯል",
    feeUpdatedReagree: "እንደገና ይስማሙ",
    rematchReturnedToLobby: "ድጋሚ ጨዋታ ተሰርዟል — ወደ ሎቢ።",
    nextRoundFee: "መግቢያ",
    updateFee: "አስቀምጥ",
    addPlayer: "ተጫዋች ጨምር",
    cancelAddPlayer: "ተጫዋች መጨመርን ሰርዝ",
    agreeAndPlay: "ተስማምተው ይጫወቱ",
    rematchStartsIn: "በ{seconds} ሰከንድ ውስጥ ይመልሱ",
    resolvingRematch: "የቀጣዩን ዙር ተጫዋቾች በማዘጋጀት ላይ...",
    rematchReady: "ዝግጁ",
    rematchWaiting: "በመጠበቅ ላይ",
    waitingForPlayers: "ተጫዋቾችን በመጠበቅ ላይ",
    rematchRemovedTitle: "ከድጋሚ ጨዋታ ተወግደዋል",
    rematchRemovedNoResponse: "በ40 ሰከንድ ውስጥ ስላልመለሱ ዝግጁ ተጫዋቾች ያለዎት ቀጥለዋል።",
    rematchRemovedBalance: "ለቀጣዩ ዙር የመግቢያ ክፍያ ቀሪ ሂሳብዎ በቂ ስላልሆነ ዝግጁ ተጫዋቾች ያለዎት ቀጥለዋል።",
    rematchLeftMessage: "ምንም ቅናሽ ሳይደረግ ከድጋሚ ጨዋታው ወጥተዋል።",
    goToLobby: "ወደ ሎቢ ሂድ",
    starting: "በመጀመር ላይ...",
    notAvailable: "የለም",
    alreadyPicked: "ካርድ አንስተዋል! ካርድ ማስቀመጥ አለብዎት።",
    mustPickFirst: "ካርድ ከማስቀመጥዎ በፊት መጀመሪያ ካርድ ያንሱ።",
    actionFailed: "ተግባሩ አልተሳካም",
    networkError: "የኔትወርክ ችግር። ከአገልጋዩ ጋር መገናኘት አልተቻለም።",
    winningHandError: "የማሸነፊያ ካርድ 4-3-3-1 መሆን አለበት።",
    visibleGameplayName: "በጨዋታ የሚታይ ስም",
    games: "ጨዋታዎች",
    amountPlayed: "የተጫወቱበት መጠን",
    shared: "የተጋራ",
    gotBirr: "ያገኙት ብር",
    rewardsLeft: "የቀረ",
    save: "አስቀምጥ",
    shareReward: "አጋራ እና Birr ያግኙ",
    share: "አጋራ",
    shareInviteText: "Carta ይጫወቱ እና Birr ያግኙ።",
    profileLoadFailed: "ፕሮፋይል መጫን አልተቻለም።",
    profileSaveFailed: "ፕሮፋይል ማስቀመጥ አልተቻለም።",
    deleteOwnRoomFirst: "አዲስ ክፍል ከመግባትዎ በፊት የራስዎን ክፍል ይሰርዙ።",
    leaveCurrentRoomFirst: "አዲስ ክፍል ከመግባትዎ በፊት አሁን ካሉበት ክፍል ይውጡ።",
    deleteOwnRoomBeforeCreate: "አዲስ ክፍል ከመፍጠርዎ በፊት የራስዎን ክፍል ይሰርዙ።",
    leaveCurrentRoomBeforeCreate: "አዲስ ክፍል ከመፍጠርዎ በፊት አሁን ካሉበት ክፍል ይውጡ።",
    invalidServerResponse: "የአገልጋይ ምላሽ ትክክል አይደለም።",
    screenshotPreviewAlt: "የተመረጠ የክፍያ ስክሪንሾት ቅድመ እይታ",
    kartaBannerAlt: "Carta ባነር {number}",
    jokerPickBlocked: "ጆከር ካርድ ከተጣለው ክምር ማንሳት አይቻልም።",
    gameProgress: "የጨዋታ ሂደት",
    totalToWin: "ለማሸነፍ ጠቅላላ",
    currentGame: "የአሁኑ ጨዋታ",
    completed: "የተጠናቀቀ",
    gameRound: "ጨዋታ {round}",
    totalAmount: "ጠቅላላ መጠን",
    noCompletedGames: "እስካሁን የተጠናቀቀ ጨዋታ የለም። መጀመሪያው አሸናፊ እስኪገኝ ድረስ መግቢያ ክፍያዎች ይመለሳሉ።",
    leaveGameTitle: "ከዚህ ጨዋታ ይውጡ?",
    leaveGameText: "የተጠናቀቁ ጨዋታዎችዎ ተስተካክለዋል። አሁን ከወጡ ከዚህ ክፍል ይወገዳሉ እና ሌላ ክፍል መፍጠር ወይም መግባት ይችላሉ።",
    leavePenaltyWarning: "ማስጠንቀቂያ፦ አሁን ከወጡ የመግቢያ ክፍያው ግማሽ ({amount}) ከሂሳብዎ ይቀነሳል እና አይመለስም።",
    confirmLeaveYes: "አዎ፣ ውጣ",
    opponentNotRespondingTitle: "ተጫዋቹ ምላሽ አይሰጥም",
    opponentNotRespondingText: "{player} ቢያንስ ለአምስት ደቂቃ አልተጫወተም።",
    leaveWithoutDeductionNotice: "አሁን ከመግቢያ ክፍያዎ ምንም ሳይቀነስ መውጣት ይችላሉ።",
    leaveWithoutDeduction: "ያለ ቅናሽ ውጣ",
    continueWaiting: "መጠበቅዎን ይቀጥሉ",
    timeoutNotReached: "የአምስት ደቂቃው ጊዜ ገና አልተጠናቀቀም። ምንም አልተቀነሰም።",
    gamesYouPlayed: "የተጫወቱት ጨዋታዎች",
    youWon: "ያሸነፉት",
    youLost: "የተሸነፉት",
    entryFeesPaid: "የተከፈለ መግቢያ ክፍያ",
    wonAndAdded: "ያሸነፉት እና የተጨመረ",
    currentRoundFee: "የአሁኑ ዙር ክፍያ",
    balanceAfterLeaving: "ከመውጣት በኋላ ቀሪ ሂሳብ",
    ok: "እሺ",
    balanceSummary: "የቀሪ ሂሳብ ማጠቃለያ",
    balanceSummaryText: "ከዚህ ክፍል ከመውጣትዎ በፊት ቀሪ ሂሳብዎን እና የጨዋታ ታሪክዎን ይመልከቱ።",
    playedWith: "የተጫወቱበት",
    totalRoomAmount: "ጠቅላላ የክፍል መጠን",
    youReceive: "የሚቀበሉት",
    youReceived: "የተቀበሉት",
    newBalance: "አዲስ ቀሪ ሂሳብ",
    gamesPlayed: "የተጫወቱ ጨዋታዎች",
    roomInactive: "ክፍሉ ንቁ አይደለም",
    yourVote: "ድምጽዎ",
    waiting: "በመጠበቅ ላይ...",
    continue: "ቀጥል",
    gamePausedWaiting: "ጨዋታው ቆሟል። ተጫዋቾችን በመጠበቅ ላይ።",
    jokerBonus: "የጆከር ቦነስ",
    jokerBonusDetail: "የጆከር ቦነስ፦ ይህ ዙር ሁለት ጊዜ ይቆጠራል",
    currentBalance: "የአሁኑ ቀሪ ሂሳብ",
    birr: "ብር",
    validHand: "ትክክለኛ ካርድ",
  },
  oromifa: {
    liveTick: "Lakkoofsa kallattii",
    settings: "Sirreeffamoota",
    language: "Afaan",
    sound: "Sagalee",
    syncingAction: "Tarkaanfiin wal-simsiifamaa jira...",
    profileView: "Mul'isa piroofaayilii",
    theme: "Bifa",
    brightMode: "Ifaa",
    darkMode: "Dukkana",
    on: "Banaa",
    off: "Cufaa",
    loading: "Fe'amaa jira...",
    user: "Fayyadamaa",
    username: "maqaa fayyadamaa",
    userNotFound: "Fayyadamaan hin argamne",
    balance: "Haftee",
    yourBalance: "Haftee kee",
    deposit: "Galchi",
    withdraw: "Baasi",
    play: "Taphadhu",
    close: "Cufi",
    english: "Ingiliffa",
    amharic: "Amaaraa",
    oromifa: "Oromifa",
    gameRooms: "Kutaalee taphaa",
    createRoom: "Kutaa uumi",
    deleteRoom: "Kutaa haqi",
    createAndJoin: "Uumi fi seeni",
    creating: "Uumaa jira...",
    join: "Seeni",
    getBack: "Deebi'i",
    inProgress: "Jira",
    joinRoom: "Kutaa seeni",
    entryFee: "Kaffaltii seensaa",
    players: "Taphattoota",
    roomName: "Maqaa kutaa",
    roomPlaceholder: "fkn., Weekend Warriors",
    gameType: "Gosa taphaa",
    visibility: "Mul'achuu",
    public: "Uummataaf",
    private: "Dhuunfaa",
    publicRoomHint: "Kutaaleen uummataa hanga guutamanitti loobiitti ni mul'atu.",
    privateRoomHint: "Kutaaleen dhuunfaa ni dhokatu; liinkii affeerraa irraa seenamuu danda'u.",
    privateLinkReady: "Liinkiin dhuunfaa qophaa'eera",
    shareTelegram: "Telegram irratti qoodi",
    copyLink: "Liinkii garagalchi",
    copied: "Garagalchame!",
    copyFailed: "Liinkii garagalchuu hin dandeenye.",
    fillAllFields: "Maaloo iddoo hunda guuti",
    failedToJoinRoom: "Kutaa seenuun hin milkoofne.",
    failedToCreateRoom: "Kutaa uumuu hin milkoofne.",
    confirmJoinTitle: "{room} seeni",
    entryFeeLabel: "Kaffaltii seensaa",
    yourBalanceLabel: "Haftee kee",
    joinNote: "Yeroo kutaa kana seentu, {amount} haftee kee irraa hir'ata.",
    insufficientBalance: "Hafteen gahaan hin jiru!",
    cancel: "Dhiisi",
    confirmAndJoin: "Mirkaneessi fi seeni",
    joining: "Seenaa jira...",
    payToNumber: "Lakkoofsa kanaaf kaffali:",
    payToNumbers: "Lakkoofsota kanaaf kaffali:",
    selectPaymentMethod: "Mala kaffaltii filadhu",
    paymentMethodRequired: "Maaloo mala kaffaltii tokko filadhu.",
    payAmountWithFollowingNumber: "Hamma kaffaltu {method} fayyadamuun lakkoofsa armaan gadiitti kaffali:",
    depositStepPay: "Mala kaffaltii filatameen lakkoofsa armaan gaditti kaffali.",
    depositStepReceipt: "Ergaa/liinkii nagahee maxxansi, yookaan suuraa kaffaltii ifa ta'e olkaa'i.",
    depositStepConfirm: "Akka kaffalte mirkaneessi, sana booda Nagahee mirkaneessi filadhu.",
    depositSuccessTitle: "Kaffaltiin milkaa'eera",
    goHome: "Gara jalqabaatti deemi",
    receiptInputType: "Gosa odeeffannoo nagahee filadhu",
    pasteTextLink: "Barreeffama/liinkii maxxansi",
    uploadScreenshot: "Suuraa iskiriinii olkaa'i",
    pasteReceiptHere: "Ergaa yookaan liinkii nagahee asitti maxxansi",
    receiptPlaceholder: "Barreeffama nagahee yookaan liinkii maxxansi...",
    uploadPaymentScreenshot: "Suuraa kaffaltii olkaa'i",
    chooseDifferentScreenshot: "Suuraa biraa filadhu",
    chooseScreenshotImage: "Suuraa iskiriinii filadhu",
    screenshotHelper: "PNG, JPG yookaan WEBP hanga 5MB",
    selected: "Filatame",
    confirmPayment: "Kaffaltii raawwadheera jedhee nan mirkaneessa",
    back: "Deebi'i",
    checkReceipt: "Nagahee mirkaneessi",
    verifying: "Mirkaneessaa jira...",
    verifyingPayment: "Kaffaltii mirkaneessaa jira...",
    confirmPaymentError: "Erguun dura saanduqa mirkaneessaa filadhu.",
    pasteReceiptError: "Maaloo ergaa yookaan liinkii nagahee kee maxxansi.",
    screenshotError: "Maaloo jalqaba suuraa iskiriinii olkaa'i.",
    receiptCheckFailed: "Mirkaneessi nagahee hin milkoofne.",
    screenshotReadFailed: "Suuraa iskiriinii dubbisuun hin danda'amne.",
    receiptComplete: "Mirkaneessi nagahee xumurame. Haala: {status}.",
    backendFailed: "API duubaa waliin wal qunnamuun hin milkoofne.",
    minWithdraw: "Baasi xiqqaa",
    maxWithdraw: "Baasi guddaa",
    dailyWithdrawalLimit: "Daangaa baasii guyyaa",
    unlimited: "Daangaa hin qabu",
    lockedGiftBalance: "Kennaa/qoodinsa hin baafamne",
    withdrawAmount: "Hamma baasuu",
    withdrawPlaceholder: "Hamma baastu galchi",
    sending: "Ergaa jira...",
    userNotTelegram: "Fayyadamaan hin argamne. Maaloo app Telegram irraa bani.",
    minWithdrawError: "Hamma baasuu xiqqaan {amount}.",
    withdrawBalanceError: "Hamma baasuu haftee baafamuu danda'u caala.",
    withdrawGamesRule: "Maallaqa baasuu dura yoo xiqqaate tapha {count} xumuri.",
    withdrawActivityRule: "Maallaqa baasuu dura guyyoota adda addaa {days} keessatti yoo xiqqaate tapha {games} taphadhu.",
    withdrawReserveRule: "Erga baaftee booda yoo xiqqaate {amount} haftee kee keessatti hambisi.",
    withdrawGamesRequiredError: "Tapha dabalataa {remaining} taphadhu. Tapha {required} erga xumurtee booda baasuu dandeessa.",
    withdrawActivityRequiredError: "Maallaqa baasuu dura taphachuu itti fufi. Guyyoota adda addaa {daysRequired} keessatti yoo xiqqaate tapha {required} xumuri. Tapha {remaining} fi guyyaa taphannaa {daysRemaining} si barbaachisa.",
    withdrawReserveError: "Erga baaftee booda yoo xiqqaate {amount} haftee kee keessatti hambisuu qabda.",
    withdrawDailyLimitError: "Daangaan baasii guyyaa kee amma {amount}.",
    withdrawFailed: "Baasiin hin milkoofne.",
    withdrawSuccess: "Gaaffiin baasuu milkaa'inaan ergame.",
    withdrawRequestSentInfo: "Gaaffiin baasii ergameera. Sa'aatii 24 gadi keessatti ni xumurama.",
    withdrawUnavailable: "Baasiin amma hin hojjetu. Maaloo yeroo biraa irra deebi'ii yaali.",
    loadingGame: "Tapha fe'aa jira...",
    fee: "Kaffaltii",
    pick: "Fuudhi",
    lay: "Keessi",
    empty: "Duwwaa",
    opponent: "Morkataa",
    player: "Taphataa",
    you: "Ati",
    waitingForCards: "Kaardota eeggachaa jira...",
    leave: "Bahi",
    win: "Mo'i",
    gameOver: "Taphi xumurame",
    victoryTitle: "Mo'atte!",
    defeatTitle: "Tapha gaarii!",
    winningCards: "Kaardota mo'ataa",
    losingCards: "Kaardota xumuraa",
    winAmount: "Hamma mo'ii",
    winner: "Mo'ataa",
    pattern: "Paaternii",
    reason: "Sababa",
    ended: "Xumurame",
    playAgain: "Ammas taphadhu",
    rematchReadyUp: "Marsaa biraatiif qophoofteettaa?",
    rematchLobby: "Loobii irra-deebii",
    joinNextRound: "Marsaa itti aanu seeni",
    recruitmentPaused: "Dhaabbate — taphataa haaraa",
    countdownHeldByCreator: "Uumaan dhaabbate",
    holdCountdown: "Dhaabi",
    resumeCountdown: "Itti fufi",
    feeUpdatedAlert: "Kaffaltiin jijjiirame",
    feeUpdatedReagree: "Irra deebi'ii waliigali",
    rematchReturnedToLobby: "Irra-deebiin haqame — loobii.",
    nextRoundFee: "Seensa",
    updateFee: "Saa'i",
    addPlayer: "Taphataa dabali",
    cancelAddPlayer: "Taphataa dabaluu dhiisi",
    agreeAndPlay: "Waliigaliitii taphadhu",
    rematchStartsIn: "Sekondii {seconds} keessatti deebisi",
    resolvingRematch: "Taphattoota marsaa itti aanu qopheessaa jira...",
    rematchReady: "Qophaa'e",
    rematchWaiting: "Eegaa jira",
    waitingForPlayers: "Taphattoota eegaa jira",
    rematchRemovedTitle: "Irra-deebii keessaa baafamte",
    rematchRemovedNoResponse: "Sekondii 40 keessatti waan hin deebineef taphattoonni qophaa'an si malee itti fufan.",
    rematchRemovedBalance: "Madaalliin kee kaffaltii marsaa itti aanuuf gahaa waan hin taaneef taphattoonni qophaa'an si malee itti fufan.",
    rematchLeftMessage: "Qarshiin osoo hin hir'atin irra-deebii keessaa baate.",
    goToLobby: "Gara loobiitti deemi",
    starting: "Jalqabaa jira...",
    notAvailable: "Hin jiru",
    alreadyPicked: "Kaardii fudhatteetta! Kaardii tokko kaa'uu qabda.",
    mustPickFirst: "Kaardii kaa'uu dura tokko fudhachuu qabda.",
    actionFailed: "Tarkaanfiin hin milkoofne",
    networkError: "Dogoggora network. Server waliin wal qunnamuun hin danda'amne.",
    winningHandError: "Harki mo'ataa 4-3-3-1 ta'uu qaba.",
    visibleGameplayName: "Maqaa tapha keessatti mul'atu",
    games: "Taphawwan",
    amountPlayed: "Hamma taphatame",
    shared: "Qoodame",
    gotBirr: "Birr argame",
    rewardsLeft: "Hafe",
    save: "Olkaa'i",
    shareReward: "Qoodi, Birr argadhu",
    share: "Qoodi",
    shareInviteText: "Carta taphadhu, Birr argadhu.",
    profileLoadFailed: "Piroofaayilii fe'uun hin danda'amne.",
    profileSaveFailed: "Piroofaayilii olkaa'uun hin danda'amne.",
    deleteOwnRoomFirst: "Kutaa kee haqiitii kutaa haaraa seeni.",
    leaveCurrentRoomFirst: "Kutaa ammaa keessaa ba'iitii kutaa haaraa seeni.",
    deleteOwnRoomBeforeCreate: "Kutaa haaraa uumuu dura kutaa kee haqi.",
    leaveCurrentRoomBeforeCreate: "Kutaa haaraa uumuu dura kutaa ammaa keessaa ba'i.",
    invalidServerResponse: "Deebiin server sirrii miti.",
    screenshotPreviewAlt: "Durargii suuraa kaffaltii filatame",
    kartaBannerAlt: "Baannerii Carta {number}",
    jokerPickBlocked: "Kaardii Joker tuula kaa'ame irraa fudhachuun hin danda'amu.",
    gameProgress: "Adeemsa taphaa",
    totalToWin: "Waliigala mo'achuuf",
    currentGame: "Tapha ammaa",
    completed: "Xumurame",
    gameRound: "Tapha {round}",
    totalAmount: "Hamma waliigalaa",
    noCompletedGames: "Taphni xumurame hanga ammaatti hin jiru. Kaffaltiin seensaa hanga mo'ataan jalqabaa argamutti deebifamuu danda'a.",
    leaveGameTitle: "Tapha kana keessaa baataa?",
    leaveGameText: "Taphawwan xumuraman kee duraan sirreeffamaniiru. Amma yoo baate, kutaa kana keessaa ni haqamta; kutaa biraa uumuu yookaan seenuu dandeessa.",
    leavePenaltyWarning: "Akeekkachiisa: Amma yoo baate, walakkaan kaffaltii seensaa ({amount}) herrega kee irraa hir'ata; hin deebifamu.",
    confirmLeaveYes: "Eeyyee, ba'i",
    opponentNotRespondingTitle: "Taphataan deebii hin kennu",
    opponentNotRespondingText: "{player} yoo xiqqaate daqiiqaa shaniif hin taphanne.",
    leaveWithoutDeductionNotice: "Amma kaffaltii seensaa kee irraa homaa osoo hin hir'atin ba'uu dandeessa.",
    leaveWithoutDeduction: "Hir'ina malee ba'i",
    continueWaiting: "Eeguu itti fufi",
    timeoutNotReached: "Yeroon daqiiqaa shanii hin geenye. Homtuu hin hir'anne.",
    gamesYouPlayed: "Taphawwan taphatte",
    youWon: "Ati moote",
    youLost: "Ati mo'amte",
    entryFeesPaid: "Kaffaltii seensaa kaffalame",
    wonAndAdded: "Mo'amee dabalame",
    currentRoundFee: "Kaffaltii marsaa ammaa",
    balanceAfterLeaving: "Haftee erga baatee booda",
    ok: "Tole",
    balanceSummary: "Cuunfaa haftee",
    balanceSummaryText: "Kutaa kana keessaa ba'uu dura haftee fi seenaa tapha kee ilaali.",
    playedWith: "Kan itti taphatte",
    totalRoomAmount: "Hamma waliigalaa kutaa",
    youReceive: "Kan ati argattu",
    youReceived: "Kan ati argatte",
    newBalance: "Haftee haaraa",
    gamesPlayed: "Taphawwan taphataman",
    roomInactive: "Kutaan hin socho'u",
    yourVote: "Sagalee kee",
    waiting: "Eegaa jira...",
    continue: "Itti fufi",
    gamePausedWaiting: "Taphi dhaabbateera. Taphattoota eegaa jira.",
    jokerBonus: "Boonsii Joker",
    jokerBonusDetail: "Boonsii Joker: marsaan kun dachaa lama lakkaa'ama",
    currentBalance: "Haftee ammaa",
    birr: "Birr",
    validHand: "Harka sirrii",
  },
};

const SettingsContext = createContext(null);

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState(() => {
    try {
      const savedSettings = localStorage.getItem("kartaSettings");
      return savedSettings ? { ...defaultSettings, ...JSON.parse(savedSettings) } : defaultSettings;
    } catch (error) {
      return defaultSettings;
    }
  });

  useEffect(() => {
    localStorage.setItem("kartaSettings", JSON.stringify(settings));
  }, [settings]);

  useEffect(() => {
    const ui = buildUi(settings.themeMode);
    const root = document.documentElement;
    const { colors } = ui;

    root.dataset.kartaTheme = ui.themeMode;
    root.style.setProperty("--karta-gold", colors.gold);
    root.style.setProperty("--karta-gold-deep", colors.goldDeep);
    root.style.setProperty("--karta-cream", colors.cream);
    root.style.setProperty("--karta-text", colors.text);
    root.style.setProperty("--karta-text-dark", colors.textDark);
    root.style.setProperty("--karta-field", colors.field);
    root.style.setProperty("--karta-bg-top", colors.bgTop);
    root.style.setProperty("--karta-bg-mid", colors.bgMid);
    root.style.setProperty("--karta-bg-low", colors.bgLow);
    root.style.setProperty("--karta-bg-base", colors.bgBase);
    root.style.setProperty("--karta-grid-gold", colors.gridGold);
    root.style.setProperty("--karta-grid-gold-x", colors.gridGoldX);
    root.style.setProperty("--karta-dot-gold", colors.dotGold);
    root.style.setProperty("--karta-dot-white", colors.dotWhite);
    root.style.setProperty("--karta-pattern-white", colors.patternWhite);
    root.style.setProperty("--karta-pattern-gold", colors.patternGold);
  }, [settings.themeMode]);

  const updateSetting = (key, value) => {
    setSettings((currentSettings) => ({
      ...currentSettings,
      [key]: value,
    }));
  };

  const value = useMemo(() => {
    const activeTranslations = translations[settings.language] || translations.english;
    const ui = buildUi(settings.themeMode);

    return {
      settings,
      updateSetting,
      ui,
      t: (key, params = {}) => {
        const template = activeTranslations[key] || translations.english[key] || key;
        return Object.entries(params).reduce(
          (text, [paramKey, paramValue]) => text.replaceAll(`{${paramKey}}`, paramValue),
          template
        );
      },
    };
  }, [settings]);

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error("useSettings must be used inside SettingsProvider");
  }

  return context;
}
